import { useState } from 'react';
import { useSellerDisputes, useDisputeMutations } from '../../features/disputes/hooks';
import { useDisputeRealtime } from '../../realtime/hooks/useDisputeRealtime';
import { Badge } from '../../components/ui/Badge'; import { Button } from '../../components/ui/Button'; import { Card } from '../../components/ui/Card'; import { EmptyState } from '../../components/ui/EmptyState'; import { Spinner } from '../../components/ui/Spinner';

export function SellerDisputesPage() {
  useDisputeRealtime(); const query = useSellerDisputes(); const { respond } = useDisputeMutations(); const [responses, setResponses] = useState<Record<string, string>>({});
  if (query.isLoading) return <Spinner label="Loading disputes…" />;
  return <div className="flex flex-col gap-4"><div><h1 className="font-display text-2xl font-semibold text-navy">Dispute desk</h1><p className="text-sm text-navy/60">Only cases tied to your stall appear here.</p></div>{!query.data?.data.length ? <EmptyState title="No open paperwork" description="No customer disputes are attached to your seller orders." /> : query.data.data.map((d) => <Card key={d.id} className="p-5"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold text-navy">Order #{d.sellerOrderId.slice(0, 8)} · {d.reason}</p><p className="text-xs text-navy/50">Opened {new Date(d.createdAt).toLocaleString()}</p></div><Badge tone="blue">{d.status.replaceAll('_', ' ')}</Badge></div><p className="mt-3 text-sm text-navy/70">{d.description}</p>{d.sellerResponse ? <p className="mt-3 rounded-xl bg-cream p-3 text-sm"><strong>Your response:</strong> {d.sellerResponse}</p> : ['OPEN','UNDER_REVIEW'].includes(d.status) && <div className="mt-3 flex gap-2"><textarea className="min-h-20 flex-1 rounded-xl border border-line p-3 text-sm" value={responses[d.id] ?? ''} onChange={(e) => setResponses((s) => ({ ...s, [d.id]: e.target.value }))} placeholder="Add a factual response for the admin" /><Button disabled={(responses[d.id]?.trim().length ?? 0) < 3} onClick={() => respond.mutate({ id: d.id, response: responses[d.id] })}>Send response</Button></div>}{d.adminResolution && <p className="mt-3 border-t border-line pt-3 text-sm text-navy"><strong>Admin resolution:</strong> {d.adminResolution}</p>}</Card>)}</div>;
}
